# 使用官方 Node.js 作为基础镜像
FROM node:current-alpine AS builder

# 设置工作目录
WORKDIR /app

# 复制 package.json 和 package-lock.json
COPY package*.json ./

# 安装依赖
RUN npm install

# 复制项目文件
COPY . .

# 构建 Next.js 项目
RUN npm run build

# 安装 Nginx
FROM nginx:alpine AS runner

# 复制构建的文件到 Nginx 的 html 目录
COPY --from=builder /app/out /usr/share/nginx/html

# 复制 Nginx 配置文件
COPY nginx.conf /etc/nginx/nginx.conf

# 暴露端口
EXPOSE 80

# 启动 Nginx
CMD ["nginx", "-g", "daemon off;"]