# 使用官方Node.js镜像作为基础镜像
FROM node:current-alpine

# 创建并设置工作目录
WORKDIR /app

# 复制package.json和package-lock.json到工作目录
COPY package*.json ./

# 安装项目依赖
RUN npm install

# 复制项目文件到工作目录
COPY . .

# 构建Next.js应用
RUN npm run build

# 设置环境变量
ENV NODE_ENV production

# 暴露端口
EXPOSE 3000

# 启动Next.js应用
CMD ["npm", "start"]
