# 使用官方 Node.js 作为基础镜像
FROM node:current-alpine AS deps

# 设置工作目录
WORKDIR /app

# 复制 package.json 和 package-lock.json
COPY package*.json ./

# 安装依赖
RUN (echo "start install deps" && npm install)

FROM node:current-alpine AS builder

WORKDIR /app

# 复制依赖
COPY --from=deps /app/node_modules ./node_modules


# 复制源代码
COPY . .

# 构建项目
RUN (echo "start build" && npm run build)

# 安装 Nginx
FROM node:current-alpine as runner

WORKDIR /app

# 设置生产环境
ENV NODE_ENV production

# 复制构建的文件到 Nginx 的 html 目录
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

# 暴露端口
EXPOSE 3000

# 启动 Nginx
CMD ["node", "server.js"]